cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'git-lfs'
brew 'git'
brew 'go'
brew 'libgit2'
brew 'node'
brew 'openssl'
brew 'pyenv-virtualenv'
brew 'pyenv'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'unrar'
brew 'youtube-dl'

cask '1password'
cask 'adium'
cask 'atom'
cask 'google-chrome'
cask 'steam'
cask 'transmission'
