alias auth-dev="source ~/.dotfiles/secrets/openstack-dev.sh"
alias auth-dev-cloud="source ~/.dotfiles/secrets/openstack-dev-cloud.sh"
alias auth-dev-s2="source ~/.dotfiles/secrets/openstack-dev-s2.sh"
alias auth-dev-hero="source ~/.dotfiles/secrets/openstack-dev-hero.sh"
alias auth-dev-t1="source ~/.dotfiles/secrets/openstack-dev-t1.sh"
alias auth-st="source ~/.dotfiles/secrets/openstack-st.sh"
alias auth-sandbox="source ~/.dotfiles/secrets/openstack-sandbox.sh"
