#!/usr/bin/env python

import sys
import subprocess

process = subprocess.Popen(["/usr/local/bin/pass", "ssh"], stdout=subprocess.PIPE)
output, error = process.communicate()

print output
sys.stdout.flush()
sys.exit(0)

